# Generated by Django 5.1 on 2024-10-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_carforrent_slug_carforsale_slug_hostelforrent_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carforrent',
            name='content',
            field=models.CharField(default='Car', max_length=100),
        ),
        migrations.AddField(
            model_name='carforsale',
            name='content',
            field=models.CharField(default='Car', max_length=100),
        ),
        migrations.AddField(
            model_name='hostelforrent',
            name='content',
            field=models.CharField(default='Hostel', max_length=100),
        ),
        migrations.AddField(
            model_name='houseforrent',
            name='content',
            field=models.CharField(default='House', max_length=100),
        ),
        migrations.AddField(
            model_name='houseforsale',
            name='content',
            field=models.CharField(default='House', max_length=100),
        ),
        migrations.AddField(
            model_name='landforsale',
            name='content',
            field=models.CharField(default='Land', max_length=100),
        ),
    ]
