# Generated by Django 5.2.6 on 2025-09-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='team_img')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['-date_added'],
            },
        ),
    ]
